apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnetdemo
  namespace: puma
rules:
  - apiGroups: ["apiVersion: v1"]         # Apply to core Kubernetes API group (api/v1)
    resources: ["deployment"]    
    verbs: ["get", "list", "watch"]