apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: ramana
spec:
  selector:
    app: dotnetdemo
    type: Loadbalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
