apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  labels:
    app: dotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: dotnet-web
        ports:
        - containerPort: 80